- app/controllers/IndexController.scala
- app/views/index.scala.html
- conf/messages.en
- conf/prod.routes
- test/controllers/IndexControllerSpec.scala
- test/views/IndexViewSpec.scala
Created test and content for start page
> Start page

- app/views/CompanyDetailsView.scala.html
- conf/messages.cy
- conf/messages.en
- test/views/CompanyDetailsViewSpec.scala
- test/views/behaviours/ViewBehaviours.scala
Updated code to add Back button on  Enter company details page.
Updated appropriate unit test also.
> DDCE-467 Added Back button on enter-company-details

- app/connectors/CtutrConnector.scala
- app/repositories/SessionRepository.scala
- app/services/DmsSubmissionService.scala
- app/views/GovukWrapper.scala.html
- project/AppDependencies.scala
- project/build.properties
- test/connectors/CtutrConnectorSpec.scala
- test/controllers/actions/DataRetrievalActionSpec.scala
- test/services/DmsSubmissionServiceSpec.scala
- test/utils/MockUserAnswers.scala
- test/utils/NavigatorSpec.scala
##Bug fix / New feature (delete as appropriate)
Removed the HMRC logo from the header in all pages and updated dependencies.
- [✓ ]  I've made every effort to commit high quality, clean code and I have executed relevant static analyses to be sure
- [✓ ]  I've executed the acceptance test pack locally to ensure there …
> DDCE-468 Removed HMRC Logo from header and updated dependencies

- app/views/CheckYourAnswersView.scala.html
- test/views/CheckYourAnswersViewSpec.scala
- test/views/IndexViewSpec.scala
##New feature 
Changed H1 to extra large. Added CheckYourAnswersViewSpec file with unit tests.
No changes in journey tests.
> DDCE-538 Added code to change H1 to xlarge

- app/assets/javascripts/google-tag-manager.js
- app/config/FrontendAppConfig.scala
- app/views/GovukWrapper.scala.html
- conf/application.conf
- project/AppDependencies.scala
Adding in setup for Google Tag Manager to migrate from Google Analytics.
[Confluence link for walkthrough](https://confluence.tools.tax.service.gov.uk/pages/viewpage.action?pageId=149687515)
> DDCE-526: Implementing Google Tag Manager snippet

- app/config/FrontendAppConfig.scala
- app/controllers/CheckYourAnswersController.scala
- app/controllers/SessionController.scala
- app/controllers/actions/DataRequiredAction.scala
- app/views/MainTemplate.scala.html
- app/views/SessionExpiredView.scala.html
- build.sbt
- conf/app.routes
- conf/application.conf
- conf/messages.cy
- conf/messages.en
- output
- test/controllers/CheckYourAnswersControllerSpec.scala
- test/controllers/SessionControllerSpec.scala
##New feature 
Changed Timeout behavior for CT-UTR. Now pop up appears if user is inactive for 15 minutes, giving an option to sign-in within 2 minutes.
The timeout page appears after 15 mins without the need of user action.
> DDCE-481 Changed timeout behavior for ctutr

- app/assets/stylesheets/partials/_palette.scss
- app/assets/stylesheets/requestcorporationtaxnumberfrontend-app.scss
##Maintenance - accessibility
Note: I have not done the dependency update as it was completed in DDCE-484 which …
> [DDCE-480] Impliment custom css for confirmation box colour

- app/views/CheckYourAnswersView.scala.html
- app/views/components/answer_row.scala.html
##Bug fix / New feature (delete as appropriate)
Updated BAck Button; Updated Wrap text of "Company Name"
> DDCE-539:updated wrap-text

- app/views/CheckYourAnswersView.scala.html
- app/views/CompanyDetailsView.scala.html
- app/views/GovukWrapper.scala.html
- app/views/MainTemplate.scala.html
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
The language toggle placement within the content div was found to be bad for screen reader users, due to the skip link moving the user to it first, rather than to the main content. In order to resolve this issue without implementing a custom template, the language toggle was moved to the bottom of the service info block, above the main "content" div.
- Were there any changes in the config? Do changes …
> [RS][DDCE-1051] Updating language toggle placement for accessibility.

- app/assets/stylesheets/partials/_palette.scss
##Bug fix
Fixed hex code for element focus state for accessibility. Required custom css to overwrite hmrc global template.
> [DDCE-1052] Fixed hex code element focus state

- app/views/MainTemplate.scala.html
As a part of this ticket I removed the article tag from all the pages in this service. The main purpose of removal of the article tag is to make sure that it's not confusing for blind/visually impaired users of the service. Whenever such users made use of the service the text 'Article' would get picked up on JAWS, VoiceOver and TalkBack. This would result in the users getting confused as they thought the word article could be the main content of the page.
As a part of the solution I made changes to the MainTemplate.scala.html where I replaced the line "mainContent = article(mainContent)" with "mainContent = mainContent". Further, I evaluated the routes for the service like '/this-service-has-been-reset', '/check-your-answers', '/enter-company-details' etc. to make sure that the article …
> DDCE-1050: Removing article tag on /ask-for-copy-of-your-corporation

- conf/application.conf
- project/AppDependencies.scala
##New feature
Upgraded version of play-ui from 8.11 to 8.12 and added accessibility configuration in application.conf
Related acceptance test PR:
https://github.com/hmrc/request-corporation-tax-number-journey-tests/pull/11
> DDCE-1057 Added code for Acessibility Statement

- project/AppDependencies.scala
##New feature 
Updated dependencies to check if Timeout Dialog has any changes regarding heading.
> DDCE-1053 Updated dependencies

- app/assets/javascripts/timeoutDialog.js
- app/views/MainTemplate.scala.html
- build.sbt
##Accessibility Issue
Added a new Timeout Dialog for the service to make heading within the modal to use H2, H1 was causing Accessibility issue.
> DDCE-1053 Added TimeoutDialog with h2

- app/assets/javascripts/google-tag-manager.js
- app/views/GovukWrapper.scala.html
##Bug fix / New feature (delete as appropriate)
> DDCE-1314: fixed gtm not using config

- project/AppDependencies.scala
##Bug fix / New feature (delete as appropriate)
> DDCE-1275: open redirect vulnerability

- .github/PULL_REQUEST_TEMPLATE.md
- app/controllers/CheckYourAnswersController.scala
- app/controllers/CompanyDetailsController.scala
- app/controllers/ConfirmationController.scala
- app/controllers/FailedToSubmitController.scala
- app/controllers/IndexController.scala
- app/controllers/SessionController.scala
- app/filters/Filters.scala
- app/filters/FiltersWithWhitelist.scala
- app/handlers/ErrorHandler.scala
- build.sbt
- conf/application.conf
- project/AppDependencies.scala
- project/plugins.sbt
- test/controllers/LanguageSwitchControllerSpec.scala
DDCE-1459: Play 2.7 Upgrade, hmrctest and artifcatory removed
Changes taken from here - https://github.com/hmrc/request-corporation-tax-number-frontend/pull/93
All I did was squash, rebase and remove the artifactory dependency.
> DDCE-1459: Play 2.7 Upgrade, hmrctest and artifcatory removed

- conf/application.conf
Zap tests failed with the 2.7 upgrade, I've created a hotfix versions and confirmed this change will fix the changes.
> DDCE-1459: Zap test fix

- app/config/FrontendAppConfig.scala
- app/controllers/LanguageSwitchController.scala
- app/filters/AllowlistFilter.scala
- app/filters/FiltersWithWhitelist.scala
- app/views/GovukWrapper.scala.html
- conf/application.conf
- project/AppDependencies.scala
- project/plugins.sbt
- test/controllers/LanguageSwitchControllerSpec.scala
Other pull requests:
- Service manager - https://github.com/hmrc/service-manager-config/pull/3286/commits/44c134ce456e28587eade2ebac6542575732b7a8
- QA - https://github.com/hmrc/app-config-qa/pull/10448
- Staging - https://github.com/hmrc/app-config-staging/pull/7533
> DDCE-1519: Tracking Consent implemented

- app/config/FrontendAppConfig.scala
- app/views/CompanyDetailsView.scala.html
- conf/application.conf
- conf/messages.cy
- conf/messages.en
- project/AppDependencies.scala
> DDCE-1546: content change on /enter-company-details

- app/views/IndexView.scala.html
- conf/messages.cy
- conf/messages.en
- project/AppDependencies.scala
- test/views/IndexViewSpec.scala
> DDCE-1581: Index page content update, minor dependency updates

- app/assets/stylesheets/partials/_base.scss
- app/config/FrontendAppConfig.scala
- app/connectors/CompanyHouseConnector.scala
- app/controllers/CheckYourAnswersController.scala
- app/controllers/CompanyDetailsController.scala
- app/controllers/CompanyDetailsNoMatchController.scala
- app/views/CompanyDetailsNoMatchView.scala.html
- app/views/ConfirmationView.scala.html
- conf/app.routes
- conf/application.conf
- conf/messages.cy
- conf/messages.en
- test/connectors/CompanyHouseConnectorSpec.scala
- test/controllers/CheckYourAnswersControllerSpec.scala
- test/controllers/CompanyDetailsNoMatchControllerSpec.scala
- test/controllers/ControllerSpecBase.scala
- test/views/CompanyDetailsNoMatchViewSpec.scala
> DDCE-1579:company house validation with a new page

- app/config/FrontendAppConfig.scala
- app/connectors/CompanyHouseConnector.scala
- app/http/ProxyHttpClient.scala
- conf/application.conf
- test/connectors/CompanyHouseConnectorSpec.scala
> DDCE-1579: squid proxy added

- app/views/CompanyDetailsNoMatchView.scala.html
- app/views/CompanyDetailsView.scala.html
- conf/messages.cy
- conf/messages.en
> DDCE-1579: links open in new tab

- README.md
Add AT link to README
That is all
> [DP][DDCE-1674] Add Acceptance tests link

- app/connectors/CompanyHouseConnector.scala
> DDCE-1579: better logging

- app/filters/AntiMimeFilter.scala
- conf/application.conf
Quick fix (I think) for the failing Zap tests.
> DDCE-1491: Added mime filter for Zap failure

- app/connectors/CompanyHouseConnector.scala
- project/AppDependencies.scala
I also made a change to the stub - https://github.com/hmrc/request-corporation-tax-number-stubs/pull/16
> DDCE-1963: Fixed duplicate Authorization header issue

- app/config/FrontendAppConfig.scala
- app/connectors/CompanyHouseConnector.scala
- app/connectors/CtutrConnector.scala
- app/controllers/CheckYourAnswersController.scala
- app/controllers/LanguageSwitchController.scala
- app/controllers/SessionController.scala
- app/controllers/actions/DataRequiredAction.scala
- app/http/ProxyHttpClient.scala
- app/models/SubmissionEvent.scala
- app/services/DmsSubmissionService.scala
- app/utils/Navigator.scala
- app/views/CheckYourAnswersView.scala.html
- app/views/CompanyDetailsView.scala.html
- app/views/GovukWrapper.scala.html
- build.sbt
- conf/app.routes
- conf/application-json-logger.xml
- conf/logback.xml
- project/AppDependencies.scala
- project/plugins.sbt
- test/controllers/CheckYourAnswersControllerSpec.scala
- test/controllers/CompanyDetailsControllerSpec.scala
- test/filters/SessionIdFilterSpec.scala
- test/forms/FormSpec.scala
- test/forms/mappings/ConstraintsSpec.scala
- test/forms/mappings/MappingsSpec.scala
- test/generators/Generators.scala
- test/services/DmsSubmissionServiceSpec.scala
- test/utils/EnumerableSpec.scala
- test/utils/NavigatorSpec.scala
Play 2.8 innit, mostly just version bumps etc.
> [DP][DDCE-2015] Play 2.8 upgrade

- app/views/CheckYourAnswersView.scala.html
- app/views/CompanyDetailsNoMatchView.scala.html
- app/views/CompanyDetailsView.scala.html
- app/views/ConfirmationView.scala.html
- build.sbt
- conf/app.routes
- project/AppDependencies.scala
- project/plugins.sbt
The move to the new hmrcNewTabLink means the links no longer have an id but this hasn't caused an issue within our journey tests so it should have no impact.
> DDCE-2344: Tabnapping fix and dependency updates

- app/views/GovukWrapper.scala.html
- conf/application.conf
Also this app-config-staging PR pls: https://github.com/hmrc/app-config-staging/pull/10869
(no other envs have related config)
> [DP][DDCE-3202] Remove unused Optimizely snippet

- conf/messages.cy
- project/AppDependencies.scala
> Update Welsh content

- app/filters/SessionIdFilter.scala
- conf/application.conf
- project/AppDependencies.scala
- run_tests.sh
- test/filters/SessionIdFilterSpec.scala
Re-added the custom session id filter, that extends a bit the functionality of the filter provided by bootstrap, to fix issue with missing session id when navigating service pages.
> DDCE-3771 | Re-added custom SessionIdFilter + cleanups.

- app/models/CompanyDetails.scala
- app/models/Date.scala
- app/models/Submission.scala
- app/views/CheckYourAnswersView.scala.html
- app/views/CompanyDetailsNoMatchView.scala.html
- app/views/CompanyDetailsView.scala.html
- app/views/ConfirmationView.scala.html
- app/views/ErrorTemplateInternalServerErrorView.scala.html
- app/views/ErrorTemplateNotFoundView.scala.html
- app/views/ErrorTemplateView.scala.html
- app/views/FailedToSubmitView.scala.html
- app/views/IndexView.scala.html
- app/views/MainTemplate.scala.html
- app/views/SessionExpiredView.scala.html
- build.sbt
- conf/application.conf
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
- test/services/DmsSubmissionServiceSpec.scala
In this PR:
- enabled CSP filter
- removed old CSP config
- cleared some warnings
- renamed govukWrapper to main_template
- added CSPNonce.attr to script tags
- updated some dependencies
> DDCE-4169 | CSP review and other minor upgrades.

- README.md
- build.sbt
- project/plugins.sbt
> DDCE-4527: Updated Readme

- app/filters/AntiMimeFilter.scala
- app/filters/SessionIdFilter.scala
- app/http/ProxyHttpClient.scala
- build.sbt
- conf/application.conf
- conf/prod.routes
- project/AppDependencies.scala
- project/build.properties
- project/plugins.sbt
- test/filters/SessionIdFilterSpec.scala
- test/views/IndexViewSpec.scala
Upgrading to Play 3.0 and modifying code as necessary in light of these changes.
> DDCE-5145: Play 3.0 upgrade

- project/AppDependencies.scala
DDCE-6828: fix bobby violation
> DDCE-6828: fix bobby violation
